window.GameEvents = {
    onPause: function(scene) {
        // ...xử lý pause game...
    },
    onResume: function(scene) {
        // ...xử lý resume game...
    },
    onEnd: function(scene) {
        // ...xử lý end game...
    }
    // ...bổ sung các event khác nếu cần...
};